# Program to find the number of distinct terms that are in the sequence generated by a^b 
# for 2 <= a <= 100, 2 <= b <= 100

numbers = set()
for a in range(2, 101):
    for b in range(2, 101):
        numbers.add(a**b)

print(len(numbers))

# answer: 9183
